name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print current working directory
        run: pwd

      - name: Print current working directory
        working-directory: ./apps/web
        run: pwd
